### ISSUE TITLE
What do we want to see on the homepage?

### ISSUE THREAD

**Issue by dtuite** [dublinjs/dublinjs.github.com#2]
I just pushed a basic [Jekyll](https://github.com/mojombo/jekyll) framework. Basically jekyll is a bunch of code for generating static pages. It is "blog aware" which means that it has features that allow it to be used as a blog pretty easily but you can make things other than blogs.

I'm confused about what we think is the optimal setup for the homepage of the DublinJS website though. At the moment, it will display the most recent post that anyone has pushed, along with a list of the 5 latest posts made, which are displayed at the bottom of the page.

I was going to make a post now with some (non-essential) general information about the presentation I'm doing on Tuesday but if I do that, it will push the meetup information off the homepage. I'd guess that the most important information we should display is the time/location of the next meetup so maybe this isn't a good idea?

We could keep the info about the next meetup displayed in the sidebar, regardless of what page the reader is on and then keep the most recent posts on the homepage for example? Another possibility is to have a dedicated "Next Meetup Info" page and put a link to it in the header? I dunno, let me know your thoughts.

**Comment by Newky** [comment]
Maybe if we have a seperate nav button for the next meeting (like we have except with the links connected up right).

We could also do with a members page, maybe a list with our twitter accounts or something like that? 

I would do some more of this but I'm not up to speed on jekyll just yet.

**Comment by josmas** [comment]
Hey guys,
both ideas are good and in general I agree that we need to keep the next meetup info always very visible. Sidebar could also have a small summary with a link to more information.
We can discuss this tomorrow after the sessions?
